### ISSUE TITLE
CMake >= 3.10 is not required

### ISSUE THREAD

**Issue by cedrusx** [emanuelev/supereight#1]
Hi, thanks for the great work!
I just verified on my Ubuntu 16.04 desktop that the code can be compiled with CMake 3.5.1. :)

**Comment by emanuelev** [comment]
Hi, thank you very much for taking the time to give it a try. I think, if my memory does not fail me, that the historical reason for CMake 3.10 is compatibility with GoogleTest gtest_add_test which you can find in se_core/tests.

**Comment by cedrusx** [comment]
Hi Emanuele, thanks for the explanation! I did not build se_core/test so I did not meet the incompatibility issue. Since CMake 3.10 is not required when building the default components using top-level makefile, I guess it might help users quickly start if relaxing the cmake_minimum_required in CMakeLists.txt besides the se_core/test folder (that's what I did).
