### ISSUE TITLE
Performance is better without OpenMP?

### ISSUE THREAD

**Issue by cedrusx** [emanuelev/supereight#2]
Hi Emanuele, I found that the overall time performance is much better when WITH_OPENMP=false. On my desktop with i7-7820X, the SDF demo runs at 4.6 FPS with OpenMP while it runs at 9.1 FPS without OpenMP. Part of the results are as below. Could you post the whole performance results at your side for comparison? Thanks a lot!

**WITH_OPENMP=true:**
    "mm2metersKernel": {
        "mean": "8893869.2687074821",
        "std": "1691929.2149056951",
        "min": "25998.0000000000",
        "max": "32270757.0000000000",
        "sum": "7844392695.0000000000"
    },
    "halfSampleRobustImageKernel": {
        "mean": "10326806.1020408161",
        "std": "3553901.1655044304",
        "min": "8919.0000000000",
        "max": "36950793.0000000000",
        "sum": "18216485964.0000000000"
    },
    ...
    "preprocessing": {
        "mean": "0.0089702493",
        "std": "0.0016953426",
        "min": "0.0000605290",
        "max": "0.0323095471",
        "sum": "7.9117598654"
    },
    "tracking": {
        "mean": "0.1326733566",
        "std": "0.0442048178",
        "min": "0.0019568520",
        "max": "1.3610136160",
        "sum": "117.0179004788"
    },
    "integration": {
        "mean": "0.0710610275",
        "std": "0.0186953274",
        "min": "0.0038445570",
        "max": "0.3619597111",
        "sum": "62.6758262888"
    },
    "raycasting": {
        "mean": "0.0163300194",
        "std": "0.0020053755",
        "min": "0.0000001560",
        "max": "0.0433384860",
        "sum": "14.4030771095"
    },
    "rendering": {
        "mean": "0.0265201778",
        "std": "0.0048889097",
        "min": "0.0001001031",
        "max": "0.0724005561",
        "sum": "23.3907968287"
    },
    "computation": {
        "mean": "0.2290346528",
        "std": "0.0501881107",
        "min": "0.0226851749",
        "max": "1.4803778040",
        "sum": "202.0085637424"
    },
    "total": {
        "mean": "0.2558666112",
        "std": "0.0509410872",
        "min": "0.0313975910",
        "max": "1.5172278449",
        "sum": "225.6743510525"
    },

**WITH_OPENMP=false:**
    "mm2metersKernel": {
        "mean": "145576.2755102041",
        "std": "22215.8069821164",
        "min": "64662.0000000000",
        "max": "457493.0000000000",
        "sum": "128398275.0000000000"
    },
    "halfSampleRobustImageKernel": {
        "mean": "105859.2176870748",
        "std": "37192.0747287784",
        "min": "18370.0000000000",
        "max": "509489.0000000000",
        "sum": "186735660.0000000000"
    },
    ...
    "preprocessing": {
        "mean": "0.0001759651",
        "std": "0.0000242558",
        "min": "0.0000818730",
        "max": "0.0006813391",
        "sum": "0.1552012601"
    },
    "tracking": {
        "mean": "0.0195451339",
        "std": "0.0017705420",
        "min": "0.0032117841",
        "max": "0.0425780261",
        "sum": "17.2388080616"
    },
    "integration": {
        "mean": "0.0233653832",
        "std": "0.0010111775",
        "min": "0.0160079770",
        "max": "0.0484527430",
        "sum": "20.6082680026"
    },
    "raycasting": {
        "mean": "0.0565673381",
        "std": "0.0029404295",
        "min": "0.0000001891",
        "max": "0.0917102970",
        "sum": "49.8923921852"
    },
    "rendering": {
        "mean": "0.0010913244",
        "std": "0.0008543340",
        "min": "0.0004929281",
        "max": "0.0955321430",
        "sum": "0.9625481515"
    },
    "computation": {
        "mean": "0.0996538203",
        "std": "0.0039080397",
        "min": "0.0315277659",
        "max": "0.1455313320",
        "sum": "87.8946695095"
    },
    "total": {
        "mean": "0.1010480457",
        "std": "0.0039370695",
        "min": "0.0323027510",
        "max": "0.1562222490",
        "sum": "89.1243762650"
    },

**Comment by emanuelev** [comment]
Hi Xuesong, sorry for the slow replies -- I am currently working at Microsoft and I am not really able to run experiments on supereight. I will do my best to find some time to run them on my laptop over the weekend. 

About the timings-- this sounds like a compilation issue, as the timings do not make sense. If you look at the preprocessing time (octree independent) the single core version is way faster than the multicore one when it really should not be the case. Can you try recompiling from scratch -- i.e. running from the root folder
> `make clean && make`

 and run the experiments again? Also, a quick way to check whether openmp is running is to look at the output of `htop`, you should see all the cores working when compiling with OpenMP.

Finally, can you provide me with the full command line that you are using?

**Comment by cedrusx** [comment]
Hi Emanuele, thanks for the reply. I downloaded a clean repo and re-build the project with and without OpenMP. This time the total time of the omp version was a little better than the no-omp version (0.070 v.s. 0.095), but still the no-omp version gave better performance on the preprocessing time and most kernels (except trackKernel). Here are the exact command lines I used:
```
git clone https://github.com/emanuelev/supereight.git
cd supereight
find -maxdepth 2 -name CMakeLists.txt -exec sed -i "s/cmake_minimum_required(VERSION 3.10)/cmake_minimum_required(VERSION 3.5)/g" {} \;

make >make-omp.log 2>&1
cp -r ../somewhere-else/living_room_traj2_loop/ .
export KERNEL_TIMINGS=1
./build/se_apps/se-denseslam-sdf-main -i living_room_traj2_loop/scene.raw -s 4.8 -p 0.34,0.5,0.24 -z 4 -c 2 -r 1 -k 481.2,-480,320,240  > benchmark-omp.log

mv build build-omp
make -e CMAKE_ARGUMENTS="-DWITH_OPENMP=false" >make-no-omp.log 2>&1
./build/se_apps/se-denseslam-sdf-main -i living_room_traj2_loop/scene.raw -s 4.8 -p 0.34,0.5,0.24 -z 4 -c 2 -r 1 -k 481.2,-480,320,240  > benchmark-no-omp.log
```
benchmark-omp.log:
>{"mm2metersKernel" : { "mean":"4126526.8049886622", "std":"1258300.6192273069", "min":"24735.0000000000", "max":"25297234.0000000000", "sum":"3639596642.0000000000"}, "halfSampleRobustImageKernel" : { "mean":"4120557.0963718821", "std":"2532080.0269672028", "min":"6531.0000000000", "max":"33868300.0000000000", "sum":"7268662718.0000000000"}, "depth2vertexKernel" : { "mean":"1590645.9901738474", "std":"2197312.5953873023", "min":"3926.0000000000", "max":"34136961.0000000000", "sum":"4208849290.0000000000"}, "vertex2normalKernel" : { "mean":"1269553.5472411187", "std":"1974697.8914136160", "min":"7169.0000000000", "max":"34677664.0000000000", "sum":"3359238686.0000000000"}, "trackKernel" : { "mean":"229699.2928207140", "std":"1261280.6837198841", "min":"11079.0000000000", "max":"33973452.0000000000", "sum":"2927517487.0000000000"}, "reduceKernel" : { "mean":"608809.0412710867", "std":"5200054.6356652267", "min":"52173.0000000000", "max":"165373181.0000000000", "sum":"7759271231.0000000000"}, "updatePoseKernel" : { "mean":"3319.6118477834", "std":"28655.2876979998", "min":"330.0000000000", "max":"3230235.0000000000", "sum":"42308453.0000000000"}, "renderDepthKernel" : { "mean":"4745841.8255945640", "std":"1836458.9525459767", "min":"39115.0000000000", "max":"34623215.0000000000", "sum":"4190578332.0000000000"}, "renderTrackKernel" : { "mean":"3270550.4122310304", "std":"1630008.8708902115", "min":"29780.0000000000", "max":"28606012.0000000000", "sum":"2887896014.0000000000"}, "renderVolumeKernel" : { "mean":"2526306.1719457014", "std":"743547.4065469640", "min":"120813.0000000000", "max":"25533210.0000000000", "sum":"558313664.0000000000"}, "frame" : { "mean":"440.5000000000", "std":"66.9768962908", "min":"0.0000000000", "max":"881.0000000000", "sum":"388521.0000000000"}, "acquisition" : { "mean":"0.0002787097", "std":"0.0000763880", "min":"0.0002171400", "max":"0.0053629649", "sum":"0.2458219416"}, "preprocessing" : { "mean":"0.0041791798", "std":"0.0012629997", "min":"0.0000586731", "max":"0.0253395450", "sum":"3.6860366152"}, "tracking" : { "mean":"0.0290172875", "std":"0.0123756634", "min":"0.0006388430", "max":"0.4430077390", "sum":"25.5932475955"}, "integration" : { "mean":"0.0170278247", "std":"0.0059617774", "min":"0.0034035321", "max":"0.2484129111", "sum":"15.0185414031"}, "raycasting" : { "mean":"0.0113423192", "std":"0.0013381437", "min":"0.0000001320", "max":"0.0419724318", "sum":"10.0039255461"}, "rendering" : { "mean":"0.0086362763", "std":"0.0034890564", "min":"0.0000804302", "max":"0.0682252068", "sum":"7.6171956763"}, "computation" : { "mean":"0.0615666113", "std":"0.0150682396", "min":"0.0108980648", "max":"0.4898673580", "sum":"54.3017511598"}, "total" : { "mean":"0.0704815973", "std":"0.0163218374", "min":"0.0116724020", "max":"0.5583435679", "sum":"62.1647687778"}, "X" : { "mean":"-0.0488035905", "std":"0.1521823221", "min":"-0.9985685349", "max":"0.8888984919", "sum":"-43.0447667837"}, "Y" : { "mean":"-0.1408059456", "std":"0.0263479035", "min":"-0.3481502533", "max":"0.0140302181", "sum":"-124.1908440590"}, "Z" : { "mean":"1.2910160068", "std":"0.2169226540", "min":"-0.0065878630", "max":"2.6797070503", "sum":"1138.6761180162"}, "tracked" : { "mean":"0.9954648526", "std":"0.0176748609", "min":"0.0000000000", "max":"1.0000000000", "sum":"878.0000000000"}, "integrated" : { "mean":"1.0000000000", "std":"0.0000000000", "min":"1.0000000000", "max":"1.0000000000", "sum":"882.0000000000"}, "raycastKernel" : { "mean":"11378252.4323094431", "std":"1326620.3080064340", "min":"4634011.0000000000", "max":"41968765.0000000000", "sum":"10001483888.0000000000"}} 

benchmark-no-omp.log:
>{"mm2metersKernel" : { "mean":"128286.7233560091", "std":"19963.1597824901", "min":"63870.0000000000", "max":"411074.0000000000", "sum":"113148890.0000000000"}, "halfSampleRobustImageKernel" : { "mean":"93199.2619047619", "std":"33723.3226648075", "min":"18477.0000000000", "max":"496973.0000000000", "sum":"164403498.0000000000"}, "depth2vertexKernel" : { "mean":"152539.4535147392", "std":"89802.9740194145", "min":"12170.0000000000", "max":"1302858.0000000000", "sum":"403619394.0000000000"}, "vertex2normalKernel" : { "mean":"438431.0098261527", "std":"248238.7467294101", "min":"36402.0000000000", "max":"3515191.0000000000", "sum":"1160088452.0000000000"}, "trackKernel" : { "mean":"963182.0018240939", "std":"870128.6394709888", "min":"74919.0000000000", "max":"5980585.0000000000", "sum":"12144761861.0000000000"}, "reduceKernel" : { "mean":"205726.7290824015", "std":"187220.1089383463", "min":"14335.0000000000", "max":"1361519.0000000000", "sum":"2594008327.0000000000"}, "updatePoseKernel" : { "mean":"4296.7281307003", "std":"2203.6142252243", "min":"480.0000000000", "max":"30244.0000000000", "sum":"54177445.0000000000"}, "renderDepthKernel" : { "mean":"324795.6591166478", "std":"27083.4110660579", "min":"235356.0000000000", "max":"1635720.0000000000", "sum":"286794567.0000000000"}, "renderTrackKernel" : { "mean":"263517.1291053228", "std":"7380.3333840080", "min":"237576.0000000000", "max":"531334.0000000000", "sum":"232685625.0000000000"}, "renderVolumeKernel" : { "mean":"1688643.3076923077", "std":"700769.6208649338", "min":"1201323.0000000000", "max":"80161655.0000000000", "sum":"373190171.0000000000"}, "frame" : { "mean":"440.5000000000", "std":"67.3371036455", "min":"0.0000000000", "max":"881.0000000000", "sum":"388521.0000000000"}, "acquisition" : { "mean":"0.0003248600", "std":"0.0000230594", "min":"0.0002420861", "max":"0.0011616731", "sum":"0.2865265398"}, "preprocessing" : { "mean":"0.0001553472", "std":"0.0000216995", "min":"0.0000812770", "max":"0.0006403329", "sum":"0.1370162265"}, "tracking" : { "mean":"0.0187713659", "std":"0.0017869637", "min":"0.0032664640", "max":"0.0403274361", "sum":"16.5563447091"}, "integration" : { "mean":"0.0229388111", "std":"0.0010279371", "min":"0.0158803500", "max":"0.0499885851", "sum":"20.2320313575"}, "raycasting" : { "mean":"0.0517138545", "std":"0.0024698322", "min":"0.0000001718", "max":"0.0882263130", "sum":"45.6116196385"}, "rendering" : { "mean":"0.0010177954", "std":"0.0007294817", "min":"0.0004860770", "max":"0.0808992989", "sum":"0.8976955484"}, "computation" : { "mean":"0.0935793786", "std":"0.0035109603", "min":"0.0294531418", "max":"0.1350325039", "sum":"82.5370119317"}, "total" : { "mean":"0.0949220340", "std":"0.0035423960", "min":"0.0302737320", "max":"0.1431738310", "sum":"83.7212340198"}, "X" : { "mean":"-0.0487192601", "std":"0.1529623046", "min":"-0.9984519482", "max":"0.8886634111", "sum":"-42.9703873992"}, "Y" : { "mean":"-0.1408721365", "std":"0.0265638661", "min":"-0.3478260040", "max":"0.0133845806", "sum":"-124.2492244244"}, "Z" : { "mean":"1.2908676472", "std":"0.2180728438", "min":"-0.0067355633", "max":"2.6794853210", "sum":"1138.5452648401"}, "tracked" : { "mean":"0.9954648526", "std":"0.0177699178", "min":"0.0000000000", "max":"1.0000000000", "sum":"878.0000000000"}, "integrated" : { "mean":"1.0000000000", "std":"0.0000000000", "min":"1.0000000000", "max":"1.0000000000", "sum":"882.0000000000"}, "raycastKernel" : { "mean":"51886733.5699658692", "std":"2337008.2907872382", "min":"37254250.0000000000", "max":"88221426.0000000000", "sum":"45608438808.0000000000"}}

Build logs:
[make-no-omp.log](https://github.com/emanuelev/supereight/files/2330942/make-no-omp.log)
[make-omp.log](https://github.com/emanuelev/supereight/files/2330943/make-omp.log)

**Comment by cedrusx** [comment]
I just found that the omp version opens 32 threads on my 8-core machine. The performance degradation might be caused by thread scheduling overhead (the process takes ~1400% CPU in total). The performance became much better when I set the number of threads to 8 by `export OMP_NUM_THREADS=8`. Cheers!
benchmark-omp-8threads.log:
>{"mm2metersKernel" : { "mean":"65291.9206349206", "std":"62201.5366463680", "min":"23485.0000000000", "max":"6192516.0000000000", "sum":"57587474.0000000000"}, "halfSampleRobustImageKernel" : { "mean":"27559.7494331066", "std":"6590.1031423188", "min":"8567.0000000000", "max":"138605.0000000000", "sum":"48615398.0000000000"}, "depth2vertexKernel" : { "mean":"29022.3790627362", "std":"12296.5080475709", "min":"4204.0000000000", "max":"311720.0000000000", "sum":"76793215.0000000000"}, "vertex2normalKernel" : { "mean":"75327.8095238095", "std":"32026.6345880870", "min":"9549.0000000000", "max":"663293.0000000000", "sum":"199317384.0000000000"}, "trackKernel" : { "mean":"158065.0362620939", "std":"152975.1963251546", "min":"15179.0000000000", "max":"4308563.0000000000", "sum":"2009480806.0000000000"}, "reduceKernel" : { "mean":"57838.7084873751", "std":"51097.2166346334", "min":"26394.0000000000", "max":"3767253.0000000000", "sum":"735303501.0000000000"}, "updatePoseKernel" : { "mean":"3348.1576339180", "std":"6889.4083434388", "min":"498.0000000000", "max":"755982.0000000000", "sum":"42565128.0000000000"}, "renderDepthKernel" : { "mean":"104875.7078142695", "std":"24281.8856211659", "min":"66732.0000000000", "max":"2399557.0000000000", "sum":"92605250.0000000000"}, "renderTrackKernel" : { "mean":"72826.9026047565", "std":"2613.0353575374", "min":"44419.0000000000", "max":"178232.0000000000", "sum":"64306155.0000000000"}, "renderVolumeKernel" : { "mean":"329701.9049773756", "std":"162652.0154120941", "min":"203700.0000000000", "max":"18616184.0000000000", "sum":"72864121.0000000000"}, "frame" : { "mean":"440.5000000000", "std":"67.0611307480", "min":"0.0000000000", "max":"881.0000000000", "sum":"388521.0000000000"}, "acquisition" : { "mean":"0.0002538277", "std":"0.0000116083", "min":"0.0002133360", "max":"0.0013398449", "sum":"0.2238760733"}, "preprocessing" : { "mean":"0.0000951773", "std":"0.0000624968", "min":"0.0000581890", "max":"0.0062281049", "sum":"0.0839464017"}, "tracking" : { "mean":"0.0035537052", "std":"0.0002718041", "min":"0.0008664590", "max":"0.0104244989", "sum":"3.1343679738"}, "integration" : { "mean":"0.0083116903", "std":"0.0008510718", "min":"0.0054446768", "max":"0.0962217150", "sum":"7.3309108680"}, "raycasting" : { "mean":"0.0112404177", "std":"0.0004005769", "min":"0.0000001881", "max":"0.0155420310", "sum":"9.9140484110"}, "rendering" : { "mean":"0.0002640542", "std":"0.0001688216", "min":"0.0001276419", "max":"0.0188119139", "sum":"0.2328958376"}, "computation" : { "mean":"0.0232009905", "std":"0.0009473794", "min":"0.0081870391", "max":"0.1004989531", "sum":"20.4632736545"}, "total" : { "mean":"0.0237188725", "std":"0.0010813465", "min":"0.0085862279", "max":"0.1206507119", "sum":"20.9200455653"}, "X" : { "mean":"-0.0492099688", "std":"0.1523366428", "min":"-0.9992357492", "max":"0.8881500959", "sum":"-43.4031925201"}, "Y" : { "mean":"-0.1409318242", "std":"0.0264146326", "min":"-0.3466522694", "max":"0.0132219791", "sum":"-124.3018689156"}, "Z" : { "mean":"1.2911017989", "std":"0.2171943424", "min":"-0.0065518618", "max":"2.6795768738", "sum":"1138.7517865896"}, "tracked" : { "mean":"0.9954648526", "std":"0.0176970899", "min":"0.0000000000", "max":"1.0000000000", "sum":"878.0000000000"}, "integrated" : { "mean":"1.0000000000", "std":"0.0000000000", "min":"1.0000000000", "max":"1.0000000000", "sum":"882.0000000000"}, "raycastKernel" : { "mean":"11275959.7622298058", "std":"361303.2725335995", "min":"7779682.0000000000", "max":"15538399.0000000000", "sum":"9911568631.0000000000"}}

The performance is similar with number of threads from 8 to 14, and drops significantly when the number is larger than 14. I am not familiar with OpenMP and I don't know why the default behavior is far from optimal...

**Comment by emanuelev** [comment]
Thanks for looking into this. 32 threads for an 8 core machine is clearly not going to give good performance. Just out of curiosity, can you paste the output of `cat /proc/cpuinfo`?

**Comment by cedrusx** [comment]
Hi Emanuele, here is the last piece of my cpuinfo:
>processor	: 15
vendor_id	: GenuineIntel
cpu family	: 6
model		: 85
model name	: Intel(R) Core(TM) i7-7820X CPU @ 3.60GHz
stepping	: 4
microcode	: 0x2000043
cpu MHz		: 1583.232
cache size	: 11264 KB
physical id	: 0
siblings	: 16
core id		: 7
cpu cores	: 8
apicid		: 15
initial apicid	: 15
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips	: 7200.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

I found that the number of working threads (which can be specified by OMP_NUM_THREADS and verified by CPU usage) is different from the number of existing threads. The latter is the former plus 16 on my machine (why?). So the default number of working threads should be 16, which makes sense because it equals to the number of processors. However some processors are occupied by other workload (compiz, Xorg, etc.) so the issue arises.

**Comment by emanuelev** [comment]
Hi Xuesong, just to let you know, I did not manage to reproduce your issue. On both my main desktop machine and on my laptop the number of threads spawn by OpenMP equals the number of hypethreaded cores. So I am not sure what is going on on your side -- can you attach a screenshot of htop with all applications but supereight filtered out?

**Comment by cedrusx** [comment]
Hi Emanuele, thanks for trying to reproduce my issue. It was compiz who always took several cores on my desktop. I have reconfigured it to make its CPU usage reasonable (from ~200% to ~40%). Now SE performs much better with the default OpenMP settings.
![selection_011](https://user-images.githubusercontent.com/17380916/45465240-e907db00-b746-11e8-8fbd-bcd15a3f4ad0.png)
