### ISSUE TITLE
Understand buildAllocationList

### ISSUE THREAD

**Issue by scl-bit** [emanuelev/supereight#49]
Hi. I'm having some troubles understanding the buildAllocationList function. What is the difference between voxel and voxelPos?

**Comment by scl-bit** [comment]
Also, if I wanted to move the position of a voxel, should I be using kPose^-1 or pose^-1?

**Comment by emanuelev** [comment]
Hi, so regarding your first question voxelPos is the metric, floating point position of the voxel, while voxel is its discrete integer counterpart (I appreciate the naming is not helpful, apologies for that). 

Regarding your second questions, I am not sure I understand, can you elaborate what you are trying to do?

**Comment by scl-bit** [comment]
Sorry, I was still a bit confused when I phrased the second question. Let me ask it differently. I have this problem: whenever I use setPose, the std::vector<Triangle> mesh used in DenseSLAMSystem::dump_mesh(const std::string filename) is empty. However, if I do not set the pose and let it be init_pose, then I get the correct mesh reconstruction (in the wrong pose obviously). In other words, Is there a way to shift the volume?

**Comment by emanuelev** [comment]
Hi sorry, for the delay, I am not sure I follow exactly what you are trying to do with setPose. Can you share more details on your pipeline? Besides, there's no mechanism to shift the volume at this moment, but one thing you can do for instance is to apply the transformation to the mesh vertexes.
