### ISSUE TITLE
Performance of the library in real environments

### ISSUE THREAD

**Issue by YoshuaNava** [emanuelev/supereight#51]
Hi Emanuele,
This is a great library, thank you very much for sharing and maintaining it.

I have some questions about the performance of the library in real environments. I hope it is OK that I ask them here, as I couldn't find any mailing list.

I would be particularly interested in knowing about:
1. The types of environments in which you have tested the library.
2. If you think that the choice of sensor and sensor model could affect the mapping process for K or O-fusion.
3. How much memory do you expect an octree to take in memory? Do you have a measure of the computational complexity of each process?
4. Resolutions that you've tested and found usable for real-time SLAM.
5. If you have measured the reconstruction error of your reconstructions, and how.
6. Any particular suggestions or aspects that you would like to see improved.

Thank you very much in advance.

Best regards,
Yoshua

**Comment by emanuelev** [comment]
Hey Yoshua,

Great to hear from you. Here are some thoughts:

1. Tested on the sequences reported in the paper + live sequences in office environment.
2. I am not sure exactly what you are referring to here, but if you are thinking of the projective map update yes, it assumes a pinhole camera model. If you are referring to performance then the sensor noise would definitely affect your choices of truncation bandwidths.
3. This is highly scene and resolution dependent of course. I've seen it ranging from tens of megabytes to high hundreds. 
4. Again, this is entirely platform dependent. In the paper we use 1cm^3 per voxel on a desktop class CPU. If you have a different tracking front-end and you are interested only on volumetric mapping you could afford finer resolution as well I think.
5. On synthetic scenes yes, code not available unfortunately. An approach I've used is to extract a mesh/point cloud from the map and use SurfReg (https://github.com/mp3guy/SurfReg) to evaluate it.
6. Many many things. Loads of opportunities from memory layout transformations, SIMD, octree compression etc. 

Hope this helps, happy to have a chat as well if you need more specific pointers.

Emanuele
