### ISSUE TITLE
About Version 2

### ISSUE THREAD

**Issue by robot-mh** [emanuelev/supereight#52]
Hi, good job. Do you have any plan to add those feature in below papers?

1. Adaptive-resolution octree-based volumetric SLAM. 3DV 2019.
2. Multi-Resolution 3D Mapping With Explicit Free Space Representation for Fast and Accurate Mobile Robot Motion Planning. RA-L, 2021.

**Comment by emanuelev** [comment]
Hi -- you can find a (very) rough implementation of 1. in the `multires-ev` branch. I'm not involved in the second paper, but I believe it's been built on a fork of this repository and it should have a much more refined implementation of 1. I'd suggest you to contact the main author and ask access to the code if possible.
