### ISSUE TITLE
error: use of ‘auto’ in lambda parameter declaration

### ISSUE THREAD

**Issue by Z-Jeff** [emanuelev/supereight#53]
When `make`, an error occurs:
`supereight/se_denseslam/src/bfusion/rendering_impl.hpp:40:36: error: use of ‘auto’ in lambda parameter declaration only available with -std=c++14 or -std=gnu++14
`
How can I fix this?

**Comment by emanuelev** [comment]
Hi, what compiler are you using and how are you trying to compile?
