### ISSUE TITLE
Simplifying pipeline configuration

### ISSUE THREAD

**Issue by sotpapathe** [emanuelev/supereight#6]
Hi! The 4 pipeline functions of DenseSLAMSystem (preprocessing, integration, tracking raycasting) need input parameters already stored in a Configuration object which is a member of DenseSLAMSystem. Wouldn't it be simpler if they received these parameters directly from the private member? A set and get member function pair could be added to allow changing the configuration during runtime. I think this would simplify the pipeline usage. Also it might make sense to change Configuration from a struct to a class so that default configuration options are set on creation. Any feedback? I could start implementing this.

**Comment by emanuelev** [comment]
Hi, thanks a lot for your input! I do agree that simplifying command line parsing / might be a good thing. However I think it would be good to keep the configuration struct/class as simple as possible.

Regarding the pipeline -- I am not a huge supporter of getter/setters to modify some internal state of the class, I'd actually decrease the size of the internal state and make things more functional oriented. But if you provide a simple sketch of what you have in mind I'm very happy to discuss it. For instance, can you give me a specific example for which you think it would be beneficial to go the getter/setter way?

**Comment by sotpapathe** [comment]
Regarding the Configuration struct, I was suggesting making it a class with public data members and a constructor applying default values to them. Essentially a struct with initial values on creation, just to avoid the initialization code.

I was thinking of changing the pipeline function prototypes to something like
```C
bool preprocessing(const ushort * inputDepth, const uint2 inputSize);
bool tracking(uint frame);
bool raycasting(uint frame);
bool integration(uint frame);
```
Since the other parameters present now are already contained in the config_ member of the pipeline object. This way however there would be no way to change the parameters stored in config_. I can think of two solutions:

1. Change config_ to a reference in the class definition so that the settings can be changed by changing the Configuration struct passed on the DenseSLAMSystem object creation.

2. Implement the following DenseSLAMSystem member functions
```C
Configuration getConfig();
void setConfig(Configuration config);
```

**Comment by emanuelev** [comment]
So let's say you want to use the library in a multi-camera scenario, in which each sensor has its own camera calibration file, position, etc.. With your proposed solution the code would alternate between changing the internal state and computation for each call to integrate. Also, I do not think that effectively hiding function parameters makes the interface clearer. If any, I would make everything explicit in the function signature.

What I think needs to be done to make the DenseSLAMSystem class more useful is to modularise the various components and assemble the pipeline at construction time: in this way we would have an SDF/Occupancy Mapper/Renderer but one shared Tracker for instance. 

Maybe @andreanicastro has some thoughts on this?

**Comment by andreanicastro** [comment]
Hi all. I agree with @emanuelev about the config setters. If there is a way to change the config using setters and getters to me doesn't make much sense to have a private member. I am also not a big fan to set the configuration in the Class itself. To me something like 
`bool preprocessing(const ushort* inputDepth, const uint2 inputSize, const Config& config)`
makes more sense. 
Actually even better
`bool preprocessing(const ushort* inputDepth, const uint2 inputSize, const PreprocessingConfig& config)`
And so on. To be honest I am not too fond of default values either. But that's probably more a personal thing. Default values tends to result in suggested configurations that do not make sense because sensors dependent.

**Comment by sotpapathe** [comment]
Thanks for the feedback! It seems that a different configuration struct for each pipeline stage would be more flexible while keeping the code easy to use/understand.

**Comment by emanuelev** [comment]
Thanks a lot, going to close this issue for the time being.
